---
- copy:
    src: files/setup_springboot.sh
    dest: /tmp/setup_springboot.sh
    mode: 0777

- name: Run setup spring-boot script
  shell: /tmp/setup_springboot.sh
  args:
    executable: /bin/bash
    